server/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :raspberries

  resources :notifications
  get 'add_raspberry' => 'notifications#add_raspberry'
  get 'build_json_array' => 'application#build_json_array'

   root 'notifications#index'

end

server/app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
end

server/app/models/notification.rb
class Notification < ActiveRecord::Base

  def self.sort(notifications)
    notifications.sort_by(&:created_at)
    notifications = notifications.to_a.reverse
  end

end

server/app/models/raspberry.rb
class Raspberry < ActiveRecord::Base
end

server/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def build_json_array
    begin      
      @notes = Notification.all
      @notes = Notification.sort(@notes)
      notifications = { json: @notes}
        respond_to do |format|
          format.html
          format.json { render notifications } 
        end
    rescue
      redirect_to root_path
    end 
  end

end

server/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    if current_user.try(:admin)
      @users = User.where(admin: false)
      flag = params[:flag]
      user_id = params[:user_id]
      if flag == "delete"
        user = User.find(user_id)
        user.destroy
        redirect_to notifications_path
      end
    elsif user_signed_in?
      @notifications = Notification.all
      @notifications = Notification.sort(@notifications)
      assignments = Assignment.where(user_id: current_user.id)
      assign = Array.new
      assignments.each {|a| assign.push(a.raspberries_id)}
      @notifications = @notifications.to_a.select {|n| assign.include?(n.unit_id)} 
    end
  end

  def add_raspberry
    if params[:flag] == "assign"
      assign = Assignment.new
      assign.user_id = params[:user_id]
      assign.raspberries_id = params[:unit_id]
      assign.save
      redirect_to add_raspberry_path(user_id: params[:user_id])
    elsif params[:flag] == "remove"
      assignments = Assignment.where(raspberries_id: params[:unit_id].to_i)
      assignments.each {|a| a.destroy }
      redirect_to add_raspberry_path(user_id: params[:user_id])
    end
    
    @user = User.find(params[:user_id])
    assignments = Assignment.where(user_id: params[:user_id])
    user_unit_ids = Array.new
    assignments.each {|a| user_unit_ids.push(a.raspberries_id)}
    @unit_ids = Raspberry.all
    @unit_ids_left = @unit_ids.to_a.select {|u| user_unit_ids.include?(u.unit_id) == false}
    @unit_ids_have = @unit_ids.to_a.select {|u| user_unit_ids.include?(u.unit_id) == true}
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new(notification_params)
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create

    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:time, :unit_id,:user_id)
    end
end

server/app/controllers/raspberries_controller.rb
class RaspberriesController < ApplicationController
  before_action :set_raspberry, only: [:show, :edit, :update, :destroy]

  # GET /raspberries
  # GET /raspberries.json
  def index
    if check_password?(params[:password])
      unit_id = params[:notification][:unit_id]
      time = params[:notification][:time]
      user = Assignment.where(raspberries_id: unit_id)
      user = user.first
      the_user = User.find(user.user_id)
      PacMailer.notification_email(the_user).deliver
      @note = Notification.new
      @note.time = time
      @note.unit_id = unit_id
      @note.save
     redirect_to notifications_path   
    end    
  end

  def check_password?(password)
    flag = false
    flag = true if password == '12345'
    flag
  end

  # GET /raspberries/1
  # GET /raspberries/1.json
  def show
  end

  # GET /raspberries/new
  def new
    @raspberry = Raspberry.new
  end

  # GET /raspberries/1/edit
  def edit
  end

  # POST /raspberries
  # POST /raspberries.json
  def create
    @raspberry = Raspberry.new
    @raspberry.unit_id = raspberry_params[:unit_id].to_i

    respond_to do |format|
      if @raspberry.save
        format.html { redirect_to root_path, notice: 'Raspberry was successfully created.' }
        format.json { render :show, status: :created, location: @raspberry }
      else
        format.html { render :new }
        format.json { render json: @raspberry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /raspberries/1
  # PATCH/PUT /raspberries/1.json
  def update
    respond_to do |format|
      if @raspberry.update(raspberry_params)
        format.html { redirect_to @raspberry, notice: 'Raspberry was successfully updated.' }
        format.json { render :show, status: :ok, location: @raspberry }
      else
        format.html { render :edit }
        format.json { render json: @raspberry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /raspberries/1
  # DELETE /raspberries/1.json
  def destroy
    @raspberry.destroy
    respond_to do |format|
      format.html { redirect_to raspberries_url, notice: 'Raspberry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raspberry
      @raspberry = Raspberry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def raspberry_params
      params.require(:raspberry).permit(:unit_id)
    end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/notifications_helper.rb
module NotificationsHelper
end

server/app/helpers/raspberries_helper.rb
module RaspberriesHelper
end

server/app/views/layouts/_navbar.html.erb
<div id="nav_bar" class="container">
  <div class="row">
    
      <% if user_signed_in? %>
       <p class="cell"><%= button_to 'Logout',destroy_user_session_path, method: :delete,class: "btn btn-default" %></p>
      <% else %>
        <p class="cell"><%= button_to 'Login', new_user_session_path, method: :get,class: "btn btn-default" %></p>
      <% end %>
    

    <% if user_signed_in? %>
      <p class="cell"><%= button_to 'Home', root_path, method: :get, class: "btn btn-default" %></p>
      <% if current_user.try(:admin) %>
        <p class="cell"><%= button_to 'Add A Raspberry PI', new_raspberry_path, method: :get,class: "btn btn-default" %></p>
      <% end %>
    
    <% require 'date' %>
    <%= link_to 'raspberry_test',raspberries_path(password: "12345",notification: {time: Time.new,unit_id: "2"}) %>
    <% end %>
  </div>
 <h1 class="text-center">Welcome to PAC Security</h1> 
</div>
<br>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="alert_box" class="container">
    <p class="notice flash"><%= notice %></p>
    <p class="alert flash"><%= alert %></p>
  </div>
  <%= render 'layouts/navbar' %>

  <%= yield %>


</body>
</html>

server/app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :unit_id %><br>
    <%= f.number_field :unit_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/notifications/add_raspberry.html.erb
<div class="container" >
  <div class="edit_border">
  <h3 class="text-center">Assign a Raspberry PI to <%= @user.try(:email) %></h3>
  <% @unit_ids_left.each do |u| %>
    <div style="width: 80%;"id="note" class="container">
      <br>
      <p>Unit ID:<%= u.unit_id%></p>
      <%= link_to 'Assign this Raspberry PI', add_raspberry_path(flag: "assign",unit_id: u.unit_id,user_id: @user.id), method: :get %>
    </div>
    <br>
  <% end %>
  </div>
  <br>
  <div class="edit_border">
  <h3 class="text-center">Remove Raspberry PI From <%= @user.try(:email) %></h3>
  <% @unit_ids_have.each do |u| %>
    <div style="width: 80%;"id="note" class="container">
      <br>
      <p>Unit ID:<%= u.unit_id%></p>
      <%= link_to 'Remove this Raspberry PI', add_raspberry_path(flag: "remove",unit_id: u.unit_id,user_id: @user.id), method: :get %>
    </div>
    <br>
  <% end %>
  </div>

</div>

server/app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

server/app/views/notifications/index.html.erb
<% if current_user.try(:admin)%>
  <% @users.each do |u| %>
    <div id="note" class="container">
      <br>
      <p>User Email: <%= u.try(:email) %></p>
      <hr>
      <%= link_to 'Delete User',notifications_path(flag: "delete",user_id: u.id) %>
      <br>
      <%= link_to 'Edit User Unit Assignments',add_raspberry_path(user_id: u.id)%>
    </div>
    <br>
  <% end %>

<% elsif user_signed_in? %>
  <% @notifications.each do |n| %>
    <div id="note" class="container">
      <p>Time: <%= n.try(:time)%></p>
      <p>Unit ID: <%= n.try(:unit_id) %></p>
      <%= button_to 'Remove Notification', notification_path(n), method: :delete %>
    </div>
    <br>
  <% end %>
<% end %>

server/app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @notification.time %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @notification.unit_id %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>

server/app/views/raspberries/_form.html.erb
<%= form_for(@raspberry) do |f| %>
  <% if @raspberry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@raspberry.errors.count, "error") %> prohibited this raspberry from being saved:</h2>

      <ul>
      <% @raspberry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field unit_style">
    <%= f.label 'Unit ID'%><br>
    <%= f.number_field :unit_id, min: 1 %>
  </div>

  <div class="actions">
    <%= f.submit 'Add Raspberry PI'%>
  </div>
<% end %>

server/app/views/raspberries/edit.html.erb
<h1>Editing raspberry</h1>

<%= render 'form' %>

<%= link_to 'Show', @raspberry %> |
<%= link_to 'Back', raspberries_path %>

server/app/views/raspberries/new.html.erb
<div class="container" >
  <h1 class="text-center">Add a Raspberry PI Unit</h1>

  <%= render 'form' %>
</div>

server/app/views/raspberries/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_raspberry_path(@raspberry) %> |
<%= link_to 'Back', raspberries_path %>